[package]
name = "reth_hl"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[lib]
name = "reth_hl"
path = "src/lib.rs"

[[bin]]
name = "reth-hl"
path = "src/main.rs"

[profile.release]
opt-level = 3
lto = "thin"
debug = "none"
strip = "symbols"
panic = "unwind"
codegen-units = 16

[profile.maxperf]
inherits = "release"
lto = "fat"
codegen-units = 1

[dependencies]
reth = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-cli = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-cli-commands = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-basic-payload-builder = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-db = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-db-api = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-chainspec = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-cli-util = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-discv4 = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-engine-primitives = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-ethereum-forks = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-ethereum-payload-builder = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-ethereum-primitives = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-eth-wire = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-eth-wire-types = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-evm = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-evm-ethereum = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-node-core = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-revm = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-network = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-network-p2p = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-network-api = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-node-ethereum = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-network-peers = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-payload-primitives = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-primitives = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-primitives-traits = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-provider = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper", features = ["test-utils"] }
reth-rpc = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-rpc-eth-api = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-rpc-engine-api = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-tracing = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-trie-common = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-trie-db = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-codecs = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-transaction-pool = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-stages-types = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-storage-api = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-errors = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-rpc-convert = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-rpc-eth-types = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-rpc-server-types = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-metrics = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-rpc-builder = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-ipc = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-rpc-layer = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
revm = { version = "29.0.1", default-features = false }

# alloy dependencies
alloy-genesis = { version = "1.0.37", default-features = false }
alloy-consensus = { version = "1.0.37", default-features = false }
alloy-chains = { version = "0.2.5", default-features = false }
alloy-eips = { version = "1.0.37", default-features = false }
alloy-evm = { version = "0.21.0", default-features = false }
alloy-json-abi = { version = "1.3.1", default-features = false }
alloy-json-rpc = { version = "1.0.37", default-features = false }
alloy-dyn-abi = "1.3.1"
alloy-network = { version = "1.0.37", default-features = false }
alloy-primitives = { version = "1.3.1", default-features = false, features = ["map-foldhash"] }
alloy-rlp = { version = "0.3.10", default-features = false, features = ["core-net"] }
alloy-rpc-types = { version = "1.0.37", features = ["eth"], default-features = false }
alloy-rpc-types-eth = { version = "1.0.37", default-features = false }
alloy-rpc-types-engine = { version = "1.0.37", default-features = false }
alloy-signer = { version = "1.0.37", default-features = false }
alloy-sol-macro = "1.3.1"
alloy-sol-types = { version = "1.3.1", default-features = false }

jsonrpsee = "0.26.0"
jsonrpsee-core = "0.26.0"
jsonrpsee-types = "0.26.0"

# misc dependencies
auto_impl = "1"
async-trait = "0.1.68"
bytes = { version = "1.5", default-features = false }
clap = { version = "4", features = ["derive"] }
cfg-if = { version = "1.0", default-features = false }
derive_more = { version = "2", default-features = false, features = ["full"] }
eyre = "0.6"
futures = "0.3"
lazy_static = "1.4.0"
once_cell = { version = "1.19", default-features = false, features = ["critical-section"] }
parking_lot = "0.12"
revm-inspectors = "0.30.0"
serde = { version = "1.0", features = ["derive"], default-features = false }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
thiserror = { version = "2.0.0", default-features = false }
tokio = { version = "1.44.2", features = ["full"] }
tokio-stream = "0.1.11"
tracing = { version = "0.1.0", default-features = false }
rmp-serde = "1.3"
lz4_flex = "0.11"
ureq = "3.0.12"
backon = { version = "1.5.2", default-features = false, features = ["std-blocking-sleep", "tokio-sleep"] }
aws-sdk-s3 = "1.93.0"
aws-config = "1.8.0"
rayon = "1.7"
time = "0.3.41"
rangemap = "=1.6.0"
http = "1"
tower = "0.5"
tower-http = { version = "0.6", features = ["cors"] }


[target.'cfg(unix)'.dependencies]
tikv-jemalloc-ctl = "0.6"
tikv-jemallocator = { version = "0.6", optional = true }
libc = "0.2"

[features]
default = ["jemalloc"]
jemalloc = ["dep:tikv-jemallocator"]
asm-keccak = [
    "reth-node-core/asm-keccak",
    "reth-primitives/asm-keccak",
]
min-debug-logs = [
    "tracing/release_max_level_debug",
]
dev = [
    "reth-cli-commands/arbitrary",
    "reth/dev",
    "revm/dev",
]

serde = [
    "alloy-chains/serde",
    "alloy-consensus/serde",
    "alloy-eips/serde",
    "alloy-primitives/serde",
    "alloy-rpc-types-engine/serde",
    "alloy-rpc-types-eth/serde",
    "bytes/serde",
    "parking_lot/serde",
    "reth-eth-wire/serde",
    "reth-eth-wire-types/serde",
    "reth-ethereum-forks/serde",
    "reth-ethereum-primitives/serde",
    "reth-network/serde",
    "reth-network-api/serde",
    "reth-primitives-traits/serde",
    "reth-revm/serde",
    "reth-trie-common/serde",
    "reth-trie-db/serde",
    "revm/serde",
]

client = [
    "jsonrpsee/client",
    "jsonrpsee/async-client",
    "reth-rpc-eth-api/client",
]

[dev-dependencies]
tempfile = "3.20.0"

[build-dependencies]
vergen = { version = "9.0.4", features = ["build", "cargo", "emit_and_set"] }
vergen-git2 = "1.0.5"

[patch.crates-io]
# alloy crates (sentioxyz fork)
alloy-consensus = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }
alloy-consensus-any = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }
alloy-contract = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }
alloy-eip5792 = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }
alloy-eip7547 = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }
alloy-eips = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }
alloy-ens = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }
alloy-genesis = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }
alloy-json-rpc = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }
alloy-network = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }
alloy-network-primitives = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }
alloy-node-bindings = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }
alloy-provider = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }
alloy-pubsub = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }
alloy-rpc-client = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }
alloy-rpc-types = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }
alloy-rpc-types-admin = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }
alloy-rpc-types-anvil = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }
alloy-rpc-types-any = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }
alloy-rpc-types-beacon = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }
alloy-rpc-types-debug = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }
alloy-rpc-types-engine = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }
alloy-rpc-types-eth = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }
alloy-rpc-types-mev = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }
alloy-rpc-types-tenderly = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }
alloy-rpc-types-trace = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }
alloy-rpc-types-txpool = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }
alloy-serde = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }
alloy-signer = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }
alloy-signer-aws = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }
alloy-signer-gcp = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }
alloy-signer-ledger = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }
alloy-signer-local = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }
alloy-signer-trezor = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }
alloy-transport = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }
alloy-transport-http = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }
alloy-transport-ipc = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }
alloy-transport-ws = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }
alloy-tx-macros = { git = "https://github.com/sentioxyz/alloy", branch = "release/v1.0.37" }

# revm crates (sentioxyz fork)
op-revm = { git = "https://github.com/sentioxyz/revm", branch = "release/v87" }
revm = { git = "https://github.com/sentioxyz/revm", branch = "release/v87" }
revm-bytecode = { git = "https://github.com/sentioxyz/revm", branch = "release/v87" }
revm-context = { git = "https://github.com/sentioxyz/revm", branch = "release/v87" }
revm-context-interface = { git = "https://github.com/sentioxyz/revm", branch = "release/v87" }
revm-database = { git = "https://github.com/sentioxyz/revm", branch = "release/v87" }
revm-database-interface = { git = "https://github.com/sentioxyz/revm", branch = "release/v87" }
revm-ee-tests = { git = "https://github.com/sentioxyz/revm", branch = "release/v87" }
revm-handler = { git = "https://github.com/sentioxyz/revm", branch = "release/v87" }
revm-inspector = { git = "https://github.com/sentioxyz/revm", branch = "release/v87" }
revm-interpreter = { git = "https://github.com/sentioxyz/revm", branch = "release/v87" }
revm-precompile = { git = "https://github.com/sentioxyz/revm", branch = "release/v87" }
revm-primitives = { git = "https://github.com/sentioxyz/revm", branch = "release/v87" }
revm-state = { git = "https://github.com/sentioxyz/revm", branch = "release/v87" }
revm-statetest-types = { git = "https://github.com/sentioxyz/revm", branch = "release/v87" }
revme = { git = "https://github.com/sentioxyz/revm", branch = "release/v87" }

# alloy-evm (sentioxyz fork)
alloy-evm = { git = "https://github.com/sentioxyz/alloy-evm", branch = "release/v0.21.2" }

# revm-inspectors (sentioxyz fork)
revm-inspectors = { git = "https://github.com/sentioxyz/revm-inspectors", branch = "release/v0.30.0" }

# reth crates (sentioxyz fork)
ef-test-runner = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
ef-tests = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
example-beacon-api-sidecar-fetcher = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
example-beacon-api-sse = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
example-bsc-p2p = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
example-custom-beacon-withdrawals = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
example-custom-dev-node = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
example-custom-engine-types = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
example-custom-evm = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
example-custom-inspector = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
example-custom-node = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
example-custom-node-components = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
example-custom-payload-builder = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
example-custom-rlpx-subprotocol = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
example-db-access = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
example-engine-api-access = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
example-exex-hello-world = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
example-exex-test = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
example-full-contract-state = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
example-manual-p2p = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
example-network = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
example-network-proxy = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
example-network-txpool = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
example-node-builder-api = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
example-node-custom-rpc = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
example-node-event-hooks = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
example-op-db-access = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
example-polygon-p2p = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
example-precompile-cache = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
example-rpc-db = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
example-txpool-tracing = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
exex-subscription = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
op-reth = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-basic-payload-builder = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-bench = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-chain-state = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-chainspec = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-cli = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-cli-commands = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-cli-runner = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-cli-util = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-codecs = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-codecs-derive = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-config = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-consensus = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-consensus-common = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-consensus-debug-client = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-db = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-db-api = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-db-common = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-db-models = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-discv4 = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-discv5 = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-dns-discovery = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-downloaders = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-e2e-test-utils = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-ecies = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-engine-local = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-engine-primitives = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-engine-service = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-engine-tree = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-engine-util = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-era = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-era-downloader = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-era-utils = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-errors = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-eth-wire = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-eth-wire-types = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-ethereum = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-ethereum-cli = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-ethereum-consensus = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-ethereum-engine-primitives = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-ethereum-forks = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-ethereum-payload-builder = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-ethereum-primitives = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-etl = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-evm = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-evm-ethereum = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-execution-errors = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-execution-types = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-exex = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-exex-test-utils = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-exex-types = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-fs-util = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-invalid-block-hooks = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-ipc = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-libmdbx = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-mdbx-sys = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-metrics = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-net-banlist = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-net-nat = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-network = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-network-api = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-network-p2p = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-network-peers = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-network-types = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-nippy-jar = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-node-api = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-node-builder = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-node-core = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-node-ethereum = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-node-ethstats = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-node-events = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-node-metrics = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-node-types = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-op = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-optimism-chainspec = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-optimism-cli = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-optimism-consensus = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-optimism-evm = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-optimism-flashblocks = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-optimism-forks = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-optimism-node = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-optimism-payload-builder = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-optimism-primitives = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-optimism-rpc = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-optimism-storage = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-optimism-txpool = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-payload-builder = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-payload-builder-primitives = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-payload-primitives = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-payload-util = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-payload-validator = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-primitives = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-primitives-traits = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-provider = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-prune = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-prune-types = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-ress-protocol = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-ress-provider = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-revm = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-rpc = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-rpc-api = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-rpc-api-testing-util = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-rpc-builder = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-rpc-convert = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-rpc-e2e-tests = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-rpc-engine-api = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-rpc-eth-api = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-rpc-eth-types = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-rpc-layer = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-rpc-server-types = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-stages = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-stages-api = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-stages-types = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-stateless = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-static-file = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-static-file-types = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-storage-api = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-storage-errors = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-storage-rpc-provider = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-tasks = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-testing-utils = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-tokio-util = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-tracing = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-tracing-otlp = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-transaction-pool = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-trie = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-trie-common = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-trie-db = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-trie-parallel = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-trie-sparse = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-trie-sparse-parallel = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
reth-zstd-compressors = { git = "https://github.com/sentioxyz/reth", branch = "release/v1.8.2-hyper" }
